### ISSUE TITLE
Cannot build with LLVM 8.0.0 or 9.0.1

### ISSUE THREAD

**Issue by sigiesec** [trailofbits/constexpr-everything#6]
When building with LLVM 8.0.0, CMake is happy with that:
```
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 8.0.0
-- Using LLVMConfig.cmake in: /usr/lib64/cmake/llvm
-- Configuring done
-- Generating done
-- Build files have been written to: /home/simon/src/constexpr-everything/build
```

but it won't build:
```
[1/2] Building CXX object CMakeFiles/constexpr-everything.dir/main.cpp.o
FAILED: CMakeFiles/constexpr-everything.dir/main.cpp.o 
/usr/lib64/ccache/c++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS  -std=c++14 -Wno-unused-parameter -Wall -Wextra -Wshadow -fno-strict-aliasing -fno-exceptions -fno-rtti   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++14 -MD -MT CMakeFiles/constexpr-everything.dir/main.cpp.o -MF CMakeFiles/constexpr-everything.dir/main.cpp.o.d -o CMakeFiles/constexpr-everything.dir/main.cpp.o -c ../main.cpp
../main.cpp: In member function ‘bool ConstexprFunctionASTVisitor::VisitFunctionDecl(clang::FunctionDecl*)’:
../main.cpp:233:11: error: ‘class clang::FunctionDecl’ has no member named ‘setConstexprKind’; did you mean ‘setConstexpr’?
  233 |     func->setConstexprKind(CSK_constexpr);
      |           ^~~~~~~~~~~~~~~~
      |           setConstexpr
../main.cpp:233:28: error: ‘CSK_constexpr’ was not declared in this scope; did you mean ‘constexpr’?
  233 |     func->setConstexprKind(CSK_constexpr);
      |                            ^~~~~~~~~~~~~
      |                            constexpr
../main.cpp: In member function ‘bool ConstexprVarDeclFunctionASTVisitor::ConstexprVarDeclVisitor::VisitDeclStmt(clang::DeclStmt*)’:
../main.cpp:279:13: warning: unused variable ‘sema’ [-Wunused-variable]
  279 |       auto &sema = CI_.getSema();
      |             ^~~~
../main.cpp: At global scope:
../main.cpp:40:6: warning: ‘bool {anonymous}::CheckConstexprDeclStmt(clang::Sema&, const clang::FunctionDecl*, clang::DeclStmt*, clang::SourceLocation&)’ defined but not used [-Wunused-function]
   40 | bool CheckConstexprDeclStmt(Sema &SemaRef, const FunctionDecl *Dcl,
      |      ^~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

I guess a newer LLVM version is required. Maybe a version check could be added to the `CMakeLists.txt` or at least the required LLVM version should be stated in the README.

**Comment by sigiesec** [comment]
With LLVM 9.0.1 (and using clang 9.0.1 as the compiler) I have no success either, I get:
```
[2/2] Linking CXX executable constexpr-everything
FAILED: constexpr-everything 
: && /home/simon/.mozbuild/clang/bin/clang++  -std=c++14 -Wno-unused-parameter -Wall -Wextra -Wshadow -fno-strict-aliasing -fno-exceptions -fno-rtti   CMakeFiles/constexpr-everything.dir/main.cpp.o  -o constexpr-everything  -lclangASTMatchers  -lclangTooling  -lclangDriver  -lclangAST  -lclangLex  -lclangParse  -lclangBasic  -lclangFrontend  -lclangEdit  -lclangAST  -lclangSerialization  -lclangSema  -lclangAST  -lclangAnalysis  -lclangASTMatchers  -lclangFrontendTool  -lclangDynamicASTMatchers  -lclangTooling  -lclangAST  -lclangASTMatchers  -lclangBasic  -lclangFrontend  -lclangLex  -lclangRewrite  -lclangRewriteFrontend  -lclangTooling  -lclangToolingCore  /home/simon/.mozbuild/clang/lib/libLLVMTransformUtils.a  /home/simon/.mozbuild/clang/lib/libLLVMAnalysis.a  /home/simon/.mozbuild/clang/lib/libLLVMTarget.a  /home/simon/.mozbuild/clang/lib/libLLVMOption.a  /home/simon/.mozbuild/clang/lib/libLLVMObject.a  /home/simon/.mozbuild/clang/lib/libLLVMBitReader.a  /home/simon/.mozbuild/clang/lib/libLLVMCore.a  /home/simon/.mozbuild/clang/lib/libLLVMSupport.a  -lclangASTMatchers  -lclangDriver  -lclangAST  -lclangLex  -lclangParse  -lclangBasic  -lclangFrontend  -lclangEdit  -lclangSerialization  -lclangSema  -lclangAnalysis  -lclangFrontendTool  -lclangDynamicASTMatchers  -lclangRewrite  -lclangRewriteFrontend  -lclangToolingCore  /home/simon/.mozbuild/clang/lib/libLLVMAnalysis.a  /home/simon/.mozbuild/clang/lib/libLLVMObject.a  /home/simon/.mozbuild/clang/lib/libLLVMBitReader.a  /home/simon/.mozbuild/clang/lib/libLLVMBitstreamReader.a  /home/simon/.mozbuild/clang/lib/libLLVMMCParser.a  /home/simon/.mozbuild/clang/lib/libLLVMProfileData.a  /home/simon/.mozbuild/clang/lib/libLLVMCore.a  /home/simon/.mozbuild/clang/lib/libLLVMRemarks.a  /home/simon/.mozbuild/clang/lib/libLLVMMC.a  /home/simon/.mozbuild/clang/lib/libLLVMBinaryFormat.a  /home/simon/.mozbuild/clang/lib/libLLVMDebugInfoCodeView.a  /home/simon/.mozbuild/clang/lib/libLLVMDebugInfoMSF.a  /home/simon/.mozbuild/clang/lib/libLLVMSupport.a  -lz  -lrt  -ldl  -lpthread  -lm  /home/simon/.mozbuild/clang/lib/libLLVMDemangle.a && :
/usr/bin/ld: CMakeFiles/constexpr-everything.dir/main.cpp.o: in function `clang::RecursiveASTVisitor<ConstexprFunctionASTVisitor>::TraverseLambdaExpr(clang::LambdaExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*)':
main.cpp:(.text._ZN5clang19RecursiveASTVisitorI27ConstexprFunctionASTVisitorE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS5_14PointerIntPairIPNS_4StmtELj1EbNS5_21PointerLikeTypeTraitsIS9_EENS5_18PointerIntPairInfoIS9_Lj1ESB_EEEEEE[_ZN5clang19RecursiveASTVisitorI27ConstexprFunctionASTVisitorE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS5_14PointerIntPairIPNS_4StmtELj1EbNS5_21PointerLikeTypeTraitsIS9_EENS5_18PointerIntPairInfoIS9_Lj1ESB_EEEEEE]+0x20f): undefined reference to `clang::LambdaExpr::getExplicitTemplateParameters() const'
/usr/bin/ld: CMakeFiles/constexpr-everything.dir/main.cpp.o: in function `clang::RecursiveASTVisitor<ConstexprVarDeclFunctionASTVisitor>::TraverseLambdaExpr(clang::LambdaExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*)':
main.cpp:(.text._ZN5clang19RecursiveASTVisitorI34ConstexprVarDeclFunctionASTVisitorE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS5_14PointerIntPairIPNS_4StmtELj1EbNS5_21PointerLikeTypeTraitsIS9_EENS5_18PointerIntPairInfoIS9_Lj1ESB_EEEEEE[_ZN5clang19RecursiveASTVisitorI34ConstexprVarDeclFunctionASTVisitorE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS5_14PointerIntPairIPNS_4StmtELj1EbNS5_21PointerLikeTypeTraitsIS9_EENS5_18PointerIntPairInfoIS9_Lj1ESB_EEEEEE]+0x20f): undefined reference to `clang::LambdaExpr::getExplicitTemplateParameters() const'
/usr/bin/ld: CMakeFiles/constexpr-everything.dir/main.cpp.o: in function `clang::RecursiveASTVisitor<ConstexprVarDeclFunctionASTVisitor::ConstexprVarDeclVisitor>::TraverseLambdaExpr(clang::LambdaExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*)':
main.cpp:(.text._ZN5clang19RecursiveASTVisitorIN34ConstexprVarDeclFunctionASTVisitor23ConstexprVarDeclVisitorEE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS6_14PointerIntPairIPNS_4StmtELj1EbNS6_21PointerLikeTypeTraitsISA_EENS6_18PointerIntPairInfoISA_Lj1ESC_EEEEEE[_ZN5clang19RecursiveASTVisitorIN34ConstexprVarDeclFunctionASTVisitor23ConstexprVarDeclVisitorEE18TraverseLambdaExprEPNS_10LambdaExprEPN4llvm15SmallVectorImplINS6_14PointerIntPairIPNS_4StmtELj1EbNS6_21PointerLikeTypeTraitsISA_EENS6_18PointerIntPairInfoISA_Lj1ESC_EEEEEE]+0x20f): undefined reference to `clang::LambdaExpr::getExplicitTemplateParameters() const'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I guess the problem here is that it still uses the system clang libraries (which are from clang 8.0.0).

**Comment by woodruffw** [comment]
Yeah, we saw similar clang version mixups in #2 and #3. Your patch in #7 should help, thanks!
